-- 1. Create the 'muscle_groups' table
CREATE TABLE muscle_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  parent INT NULL -- Self-referencing for hierarchical groups, NULL for top-level groups
);

-- 2. Insert initial data into 'muscle_groups'
INSERT INTO muscle_groups (id, name, parent) VALUES
(1, 'Chest', NULL),
(2, 'Shoulders', NULL),
(3, 'Arms', NULL),
(4, 'Back', NULL),
(5, 'Core', NULL),
(6, 'Legs', NULL),
(7, 'Upper Chest', 1),
(8, 'Lower Chest', 1),
(9, 'Front Deltoids', 2),
(10, 'Side Deltoids', 2),
(11, 'Rear Deltoids', 2),
(12, 'Rotator Cuff', 2),
(13, 'Traps', 2),
(14, 'Triceps', 3),
(15, 'Biceps', 3),
(16, 'Forearms & Grip', 3),
(17, 'Lats', 4),
(18, 'Rhomboids', 4),
(19, 'Lower Back', 4),
(20, 'Abdominals', 5),
(21, 'Obliques', 5),
(22, 'Quads', 6),
(23, 'Hamstrings', 6),
(24, 'Glutes', 6),
(25, 'Calves', 6);

-- Set sequence to continue from the last ID
SELECT setval('muscle_groups_id_seq', (SELECT MAX(id) FROM muscle_groups));


-- 3. Create the 'exercise_definitions' table (formerly 'workouts')
CREATE TABLE exercise_definitions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  details TEXT,
  primary_muscle_group INT NOT NULL,
  secondary_muscle_groups INT[],

  -- Foreign key constraint for primary_muscle_group
  CONSTRAINT fk_primary_muscle_group
    FOREIGN KEY (primary_muscle_group)
    REFERENCES muscle_groups(id)
    ON DELETE RESTRICT
);

-- 4. Insert initial data into 'exercise_definitions'
INSERT INTO exercise_definitions (id, name, details, primary_muscle_group, secondary_muscle_groups) VALUES
(1, 'Bench Press (15kg)', '3 sets of 8 reps', 8, ARRAY[14, 9]),
(2, 'Incline Bench Press', '3 sets of 8 reps', 7, ARRAY[9, 14]),
(3, 'Push-ups & Variations', '3 sets to failure', 8, ARRAY[9, 14, 20]),
(4, 'Straight Bar Dips', '3 sets to failure', 8, ARRAY[9, 14]),
(5, 'Overhead Press', '3 sets of 8 reps', 9, ARRAY[14, 7, 13]),
(6, 'Lateral Raise (5kg)', '3 sets of 12 reps', 10, ARRAY[9, 11, 13]),
(7, 'Pike Push-ups', '3 sets of 5 reps', 9, ARRAY[14, 7]),
(8, 'Egyptian Raise', '3 sets of 10 reps', 11, ARRAY[12, 13]),
(9, 'Handstand Hold', '3x30 sec holds', 9, ARRAY[14, 13, 20]),
(10, 'Pull-ups (Weighted 15kg)', '3 sets of 8 reps', 17, ARRAY[15, 13, 10, 20]),
(11, 'Chin-ups (Weighted 15kg)', '3 sets of 8 reps', 17, ARRAY[15, 16, 13]),
(12, 'Bent-over Barbell Row', '3 sets of 8 reps', 17, ARRAY[15, 10]),
(13, 'Seated Cable Row', '3 sets of 10 reps', 17, ARRAY[15, 10]),
(14, 'Lat Pulldown', '3 sets of 10 reps', 17, ARRAY[15, 13, 18]),
(15, 'Low Bar Transitions / Negative Muscle Ups', '3 sets to failure', 8, ARRAY[14, 20, 1]),
(16, 'Ring Curl / Pelican Curl', '3 sets of 10 reps', 15, ARRAY[16, 17]),
(17, 'Barbell Back Squat', '3 sets of 8 reps', 22, ARRAY[24, 23, 20]),
(18, 'Romanian Deadlift', '3 sets of 8 reps', 23, ARRAY[24, 19]);

-- Set sequence to continue from the last ID
SELECT setval('exercise_definitions_id_seq', (SELECT MAX(id) FROM exercise_definitions));


-- 5. Create the 'workout_plans' table
CREATE TABLE workout_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Create the 'workout_plan_exercises' join table
CREATE TABLE workout_plan_exercises (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workout_plan_id BIGINT NOT NULL,
  exercise_definition_id BIGINT NOT NULL,
  sets INT,
  reps INT,
  weight DECIMAL,
  "order" INT, -- To define the order of exercises within a plan
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  -- Foreign key to workout_plans
   CONSTRAINT fk_workout_plan
     FOREIGN KEY (workout_plan_id)
     REFERENCES workout_plans(id)
     ON DELETE CASCADE,

   -- Foreign key to exercise_definitions
   CONSTRAINT fk_exercise_definition
     FOREIGN KEY (exercise_definition_id)
     REFERENCES exercise_definitions(id)
     ON DELETE RESTRICT
 );